[package]
name = "pzcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.5"
log = { version = "0.4.22", features = ["std"] }
tokio = { version = "1.42.0", features = ["full"] }
